### ISSUE TITLE
`@media screen and (max-width: env(--size-breakpoint-s)) {` breaks highlighting

### ISSUE THREAD

**Issue by jasikpark** [csstools/postcss-language#15]
Type: <b>Bug</b>

Create a css file w/ 

```css

.NetworkCopyButton_idContainer,
.NetworkCopyButton_cidrContainer {
  position: absolute;
  inset: 0;
  display: inline-flex;
  gap: 1ch;
  align-items: center;
  justify-content: flex-start;
  padding-left: 12px;
  padding-right: 12px;
  width: calc(100% - 24px);

  @media screen and (max-width: env(--size-breakpoint-s)) {
    justify-content: center;
  }
}
```

in the source. content below the env variable will not be highlighted.

Extension version: 1.0.9
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|20, 13, 13|
|Memory (System)|64.00GB (24.57GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>
