### ISSUE TITLE
Using `env(--size-breakpoint-xs)` in a nested media query breaks highlighting

### ISSUE THREAD

**Issue by jasikpark** [csstools/postcss-language#17]
Type: <b>Bug</b>

Load 

```css
.UpgradeBanner {
  position: relative;
  isolation: isolate;
  display: flex;
  gap: 8px;
  justify-content: space-between;
  align-content: center;
  padding: 32px;
  color: white;
  border-radius: 8px;
  overflow: hidden;
  background: linear-gradient(90deg, var(--color-purple-50) 0%, var(--color-purple-30) 100%);

  @media screen and (width <= env(--size-breakpoint-xs)) {
    padding: 24px;
  }
}

.UpgradeBanner_heading {
  font-size: var(--font-size-h2);

  @media screen and (width <= env(--size-breakpoint-xs)) {
    font-size: var(--font-size-h3);
  }
}
```

in VSCode, and notice that the text after the first nested media query is not tree-sitter highlighted.

Extension version: 1.0.9
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:38:28.722Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 9, 8|
|Memory (System)|64.00GB (16.86GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>
